require_relative 'config/environment.rb'
require 'sinatra/activerecord/rake'

desc "Print hello"
task :hello_world do 
    puts "Hello World"
end

desc "Seeds the DB with some visitors, dinasours, and food"
task :seed do 
    sh 'rm jurassic_park.db'
    sh 'ruby seeds.rb'
end

desc "Lauches a console session"
task :console do
    [:seed]
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    Pry.start
end